imagePullSecrets:
  - name: regcred

imagePullPolicy: IfNotPresent

simulation:
  OE_SIMULATION: "1"

web:
  image: ghcr.io/edgelesssys/emojivoto/web
  imageVersion: v0.4.0
  tlsServer: enabled

emoji:
  image: ghcr.io/edgelesssys/emojivoto/emoji-svc
  imageVersion: v0.4.0

voting:
  image: ghcr.io/edgelesssys/emojivoto/voting-svc
  imageVersion: v0.4.0
