imagePullSecrets:
  - name: regcred

imagePullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m

simulation:
  OE_SIMULATION: "0"

web:
  image: ghcr.io/edgelesssys/emojivoto/web
  imageVersion: v0.2.0
  tlsServer: enabled

emoji:
  image: ghcr.io/edgelesssys/emojivoto/emoji-svc
  imageVersion: v0.2.0

voting:
  image: ghcr.io/edgelesssys/emojivoto/voting-svc
  imageVersion: v0.2.0

