imagePullSecrets:
  - name: regcred

imagePullPolicy: Always

resources:
  requests:
    cpu: 100m

simulation:
  OE_SIMULATION: "0"

resourceInjection: "enabled"

web:
  image: ghcr.io/edgelesssys/emojivoto/web
  imageVersion: v0.5.0

emoji:
  image: ghcr.io/edgelesssys/emojivoto/emoji-svc
  imageVersion: v0.5.0

voting:
  image: ghcr.io/edgelesssys/emojivoto/voting-svc
  imageVersion: v0.5.0
