imagePullSecrets:
  - name: regcred

imagePullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m

simulation:
  OE_SIMULATION: "0"

resourceInjection: "enabled"

dcap:
  pccsUrl: ""
  useSecureCert: ""

web:
  image: ghcr.io/edgelesssys/emojivoto/web
  imageVersion: v0.7.0

emoji:
  image: ghcr.io/edgelesssys/emojivoto/emoji-svc
  imageVersion: v0.7.0

voting:
  image: ghcr.io/edgelesssys/emojivoto/voting-svc
  imageVersion: v0.7.0
